services:
  - type: web
    name: file0share-dev
    env: node
    plan: free
    buildCommand: ./deploy.sh
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_APP_URL
        value: https://file-share-dev.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: jarvis-db
          property: connectionString




