CREATE TABLE IF NOT EXISTS pages (
  slug TEXT PRIMARY KEY,
  content TEXT DEFAULT '',
  isProtected INTEGER DEFAULT 0,
  passwordHash TEXT DEFAULT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  ownerId TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS files (
  fileId TEXT PRIMARY KEY,
  slug TEXT NOT NULL,
  originalName TEXT NOT NULL,
  storedName TEXT NOT NULL,
  mimetype TEXT NOT NULL,
  size INTEGER NOT NULL,
  downloadURL TEXT NOT NULL,
  uploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (slug) REFERENCES pages(slug) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE,
  name TEXT,
  razorpayCustomerId TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id TEXT PRIMARY KEY,
  userId TEXT,
  status TEXT,
  plan TEXT,
  currentPeriodEnd DATETIME,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
