name = "sharefile"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "file-share-db"
database_id = "0df66010-19eb-4409-9733-0f89c8a7c0d2"


